[package]
name = "rust-openttd-admin"
version = "0.1.0"
authors = ["Thomas den Hollander <denhollander.thomas@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
failure = "0.1.5"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
